"use strict";
exports.__esModule = true;
var tcxFile_1 = require("./dist/classes/tcxFile");
exports.TcxFile = tcxFile_1.TcxFile;
var activity_1 = require("./dist/classes/activity");
exports.Activity = activity_1.Activity;
var geoPoint_1 = require("./dist/classes/geoPoint");
exports.GeoPoint = geoPoint_1.GeoPoint;
var gpsPoint_1 = require("./dist/classes/gpsPoint");
exports.GpsPoint = gpsPoint_1.GpsPoint;
var author_1 = require("./dist/classes/author");
exports.Author = author_1.Author;
var creator_1 = require("./dist/classes/creator");
exports.Creator = creator_1.Creator;
var lap_1 = require("./dist/classes/lap");
exports.Lap = lap_1.Lap;
var consts = require("./dist/classes/consts");
exports.consts = consts;
